"""
Domain signals for the trading system.
"""

from dataclasses import dataclass
from datetime import datetime

@dataclass(frozen=True)
class VolSignal:
    """Represents a volatility signal generated by a model."""
    instrument_token: int
    kind: str
    strength: float
    timestamp: datetime